# Generated by Django 3.0.5 on 2020-04-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200429_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('BOOKS ', 'BOOKS'), ('LAB ACCESSORIES', 'LAB ACCESSORIES'), ('ELECTRONICS', 'ELECTRONICS')], default='', max_length=20),
        ),
    ]
