# Generated by Django 3.0.5 on 2020-07-06 05:07

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200701_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='profile_pics'),
        ),
    ]
