# Generated by Django 3.0.5 on 2020-04-25 15:04

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='mobile',
        ),
        migrations.AddField(
            model_name='signup',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AlterField(
            model_name='signup',
            name='year',
            field=models.IntegerField(),
        ),
    ]
