# Generated by Django 3.0.5 on 2020-05-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='branch',
            field=models.CharField(choices=[('CSE', 'CSE'), ('IT', 'IT'), ('CSI', 'CSI'), ('CO', 'CO'), ('CE', 'CE'), ('ECE', 'ECE'), ('EN', 'EN'), ('ME', 'ME'), ('OTHERS', 'OTHERS')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='year',
            field=models.CharField(choices=[('I', 'FIRST'), ('II', 'SECOND'), ('III', 'THIRD'), ('IV', 'FOURTH')], default='', max_length=6),
        ),
    ]
