# Generated by Django 3.0.5 on 2020-05-12 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200503_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='year',
        ),
    ]
