# Generated by Django 3.0.5 on 2020-05-14 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userprofile_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid', message='Invalid', regex='^[0-9]{10}*$')]),
        ),
    ]
