# Generated by Django 3.0.5 on 2020-05-15 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200515_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_number',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(code='Invalid', message='Invalid mobile number entered', regex='^[6789][0-9]{9}$')]),
        ),
    ]
