# Generated by Django 3.0.5 on 2020-06-01 05:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200515_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='Invalid', message='Invalid mobile number entered', regex='^[6789][0-9]{9}$')]),
        ),
    ]
